---
- connection: local
  hosts: localhost

  vars:
    base_dir: ~/tmp/h
    cask_packages:
      common:
        - pycharm-ce
      work:
        - intellij-idea
        - pycharm

  tasks:
    - name: create base dir
      file:
        path: "{{ base_dir }}"
        state: directory
    - name: clone dotfiles
      git:
        repo: git@github.com:lepistone/dotfiles
        dest: "{{ base_dir }}/dotfiles"
    - name: install brew packages
      homebrew:
        name:
          - ansible
          - bash
          - curl
          - fd
          - fzf
          - git
          - jq
          - kube-ps1
          - kubernetes-cli
          - less
          - libressl
          - maven
          - mosh
          - nethack
          - openssh
          - openssl
          - pstree
          - python
          - ripgrep
          - tmux
          - tree
          - youtube-dl
          - zsh
          - zsh-syntax-highlighting
          # - zsh-completions  TODO needs setup
    - name: install cask packages
      homebrew_cask:
        name:
          - 1password
          - docker
          - firefox
          - font-jetbrains-mono
          - godot
          - google-cloud-sdk
          - gpg-suite
          - intellij-idea-ce
          - iterm2
          - macvim
          - mullvadvpn
          - obs
          - rectangle
          - skype
          - signal
          - steam
          - telegram
          - tomighty
          - vlc
