---
- connection: local
  hosts: localhost

  vars:
    base_dir: ~/tmp/h
    brew_packages:
      common:
        - git
        - tree
        - gnupg
        - heroku
        - httpie
        - jq
        - libmemcached
        - libressl
        - maven
        - mysql
        - node
        - postgresql
        - pstree
        - python
        - python3
        - reattach-to-user-namespace
        - ruby
        - the_silver_searcher
        - tmux
        - tree
        - vim
        - youtube-dl
        - zsh
        - zsh-syntax-highlighting
      work:
        - hmtools
      home: []

    cask_packages:
      common:
        - 1password
        - calibre
        - docker
        - dropbox
        - font-inconsolata-dz
        - google-chrome
        - iterm2
        - java
        - kindle
        - skype
        - spectacle
        - spotify
        - steam
        - vagrant
        - virtualbox
        - virtualbox-extension-pack
        - vlc
      home:
        - intellij-idea-ce
        - pycharm-ce
      work:
        - intellij-idea
        - pycharm

  tasks:
    - name: create base dir
      file:
        path: "{{ base_dir }}"
        state: directory
    - name: clone dotfiles
      git:
        repo: git@github.com:lepistone/dotfiles
        dest: "{{ base_dir }}/dotfiles"
    - name: install brew packages
      homebrew:
        name: "{{ item }}"
      with_items: "{{ brew_packages.common }} + {{ brew_packages.home }}"
    - name: install cask packages
      homebrew_cask:
        name: "{{ item }}"
      with_items: "{{ cask_packages.common }} + {{ cask_packages.home }}"
